/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiosIndexRouteImport } from './routes/studios.index'
import { Route as StudiosStudioIdRouteImport } from './routes/studios.$studioId'
import { Route as StudioDashboardRouteImport } from './routes/studio.dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosIndexRoute = StudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosStudioIdRoute = StudiosStudioIdRouteImport.update({
  id: '/studios/$studioId',
  path: '/studios/$studioId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDashboardRoute = StudioDashboardRouteImport.update({
  id: '/studio/dashboard',
  path: '/studio/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/studios/': typeof StudiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/studios': typeof StudiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/studios/': typeof StudiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/terms'
    | '/studio/dashboard'
    | '/studios/$studioId'
    | '/studios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/terms'
    | '/studio/dashboard'
    | '/studios/$studioId'
    | '/studios'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/terms'
    | '/studio/dashboard'
    | '/studios/$studioId'
    | '/studios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  TermsRoute: typeof TermsRoute
  StudioDashboardRoute: typeof StudioDashboardRoute
  StudiosStudioIdRoute: typeof StudiosStudioIdRoute
  StudiosIndexRoute: typeof StudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/': {
      id: '/studios/'
      path: '/studios'
      fullPath: '/studios/'
      preLoaderRoute: typeof StudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/$studioId': {
      id: '/studios/$studioId'
      path: '/studios/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof StudiosStudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/dashboard': {
      id: '/studio/dashboard'
      path: '/studio/dashboard'
      fullPath: '/studio/dashboard'
      preLoaderRoute: typeof StudioDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  TermsRoute: TermsRoute,
  StudioDashboardRoute: StudioDashboardRoute,
  StudiosStudioIdRoute: StudiosStudioIdRoute,
  StudiosIndexRoute: StudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
